-- MySQL Script generated by MySQL Workbench
-- Sat Mar 14 23:53:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Model4_1_Drach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Model4_1_Drach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Model4_1_Drach` DEFAULT CHARACTER SET utf8 ;
USE `Model4_1_Drach` ;

-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`Склади`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`Склади` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`Склади` (
  `ID` INT NOT NULL,
  `НазваСкладу` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`Товари`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`Товари` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`Товари` (
  `ID` INT NOT NULL,
  `Артикул` VARCHAR(45) NULL,
  `НазваТовару` VARCHAR(45) NOT NULL,
  `КодУктЗед` VARCHAR(45) NOT NULL,
  `Одиниці` VARCHAR(45) NOT NULL,
  `Склади_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Склади_ID`),
  INDEX `fk_Товари_Склади1_idx` (`Склади_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Товари_Склади1`
    FOREIGN KEY (`Склади_ID`)
    REFERENCES `Model4_1_Drach`.`Склади` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`ВмістНакладної`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`ВмістНакладної` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`ВмістНакладної` (
  `ID` INT NOT NULL,
  `КількістьТовару` DECIMAL(10,2) NOT NULL,
  `ЦінаЗпдв` DECIMAL(7,2) NOT NULL,
  `СумаЗпдв` DECIMAL(7,2) NOT NULL,
  `Товари_ID` INT NOT NULL,
  `Товари_Склади_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ВмістНакладної_Товари1_idx` (`Товари_ID` ASC, `Товари_Склади_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ВмістНакладної_Товари1`
    FOREIGN KEY (`Товари_ID` , `Товари_Склади_ID`)
    REFERENCES `Model4_1_Drach`.`Товари` (`ID` , `Склади_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`Покупець`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`Покупець` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`Покупець` (
  `ID` INT NOT NULL,
  `Прізвище` VARCHAR(45) NOT NULL,
  `Ім'я` VARCHAR(45) NOT NULL,
  `Побатькові` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`Постачальники`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`Постачальники` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`Постачальники` (
  `ID` INT NOT NULL,
  `Назва` VARCHAR(45) NOT NULL,
  `ПоточнийРахунок` VARCHAR(45) NOT NULL,
  `НазваБанку` VARCHAR(45) NOT NULL,
  `МФО` INT NOT NULL,
  `ЄДРПОУ` INT NOT NULL,
  `ІПН` VARCHAR(45) NOT NULL,
  `НомерСвідоцтва` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model4_1_Drach`.`Накладна`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model4_1_Drach`.`Накладна` ;

CREATE TABLE IF NOT EXISTS `Model4_1_Drach`.`Накладна` (
  `ID` INT NOT NULL,
  `ВидДоговору` VARCHAR(45) NOT NULL,
  `Дата` DATE NOT NULL,
  `ВмістНакладної_ID` INT NOT NULL,
  `Покупець_ID` INT NOT NULL,
  `Постачальники_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `ВмістНакладної_ID`, `Покупець_ID`),
  INDEX `fk_Накладна_ВмістНакладної1_idx` (`ВмістНакладної_ID` ASC) VISIBLE,
  INDEX `fk_Накладна_Покупець1_idx` (`Покупець_ID` ASC) VISIBLE,
  INDEX `fk_Накладна_Постачальники1_idx` (`Постачальники_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Накладна_ВмістНакладної1`
    FOREIGN KEY (`ВмістНакладної_ID`)
    REFERENCES `Model4_1_Drach`.`ВмістНакладної` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Накладна_Покупець1`
    FOREIGN KEY (`Покупець_ID`)
    REFERENCES `Model4_1_Drach`.`Покупець` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Накладна_Постачальники1`
    FOREIGN KEY (`Постачальники_ID`)
    REFERENCES `Model4_1_Drach`.`Постачальники` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
